seed_everything: 42
trainer:
  enable_checkpointing: true
  gradient_clip_val: 1.
  max_epochs: 100
  precision: 16-mixed
  callbacks:
    - class_path: LearningRateMonitor
      init_args:
        logging_interval: "step"
    - class_path: ModelCheckpoint
      init_args:
        save_last: true
        save_top_k: -1
        every_n_epochs: 1
        monitor: "val_loss_nologit"
        auto_insert_metric_name: false
        filename: "epoch-{epoch:03d}"
  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: null
      name: "logs"
  detect_anomaly: false
model:
  class_path: astroclip.models.astroclip.AstroClipModel
  init_args:
    temperature: 15.5
    logit_scale: 15.5
    image_encoder:
      class_path: astroclip.models.astroclip.CachedImageHead
      init_args:
        embed_dim: 512
        n_head: 4
        model_embed_dim: 1024
        dropout: 0.1
    spectrum_encoder:
      class_path: astroclip.models.astroclip.CachedSpectrumHead
      init_args:
        embed_dim: 512
        n_head: 4
        model_embed_dim: 768
        dropout: 0.1
data:
  class_path: astroclip.data.cached_datamodule.CachedAstroClipBatchDataloader
  init_args:
    data_path: null
    train_start: null
    train_stop: null
    val_start: null
    val_stop: null
    batch_size: 1024
    num_workers: 2
    drop_last: true
    pin_memory: true
    shuffle: true
    prefetch_factor: 1
    persistent_workers: true
optimizer:
  class_path: torch.optim.adamw.AdamW
  init_args:
    lr: 1e-4
    weight_decay: 0.01
lr_scheduler:
  class_path: astroclip.CosineAnnealingWithWarmupLR
  init_args:
    T_max: 10_000
    T_warmup: 1_000
    eta_min: ${eval:'${optimizer.init_args.lr}//500'}
